# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-18 13:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PageSubscriptions',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('feed_subscription', models.BooleanField(default=False)),
                ('messenger_subscription', models.BooleanField(default=False)),
            ],
        ),
    ]
