# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-22 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessTokens',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('access_token', models.CharField(max_length=255)),
            ],
        ),
    ]
