# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-11 16:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20180511_1938'),
        ('hatespeech', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletedComments',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('deleted_comment', models.CharField(max_length=1024)),
                ('page_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Page')),
            ],
        ),
    ]
