# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-12 15:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hatespeech', '0002_deletedcomments'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DeletedComments',
            new_name='DeletedPageComments',
        ),
        migrations.RenameField(
            model_name='deletedpagecomments',
            old_name='page_id',
            new_name='page',
        ),
    ]
